### ISSUE TITLE
weird crash with the mod quark.

### ISSUE THREAD

**Issue by meelock** [CD4017BE/InductiveAutomation#10]
when i open up the steam crafter thingy, it crashes with the error (it has been shortened for readabity):
Client thread/ERROR]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$InitGuiEvent$Post@1a26af22:
java.lang.AbstractMethodError
    at vazkii.quark.base.handler.DropoffHandler.isValidChest(DropoffHandler.java:120) ~[DropoffHandler.class:?]
    at vazkii.quark.management.feature.ChestButtons.initGui(ChestButtons.java:57) ~[ChestButtons.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_457_ChestButtons_initGui_Post.invoke(.dynamic) ~[?:?]

**Comment by Tander** [comment]
B:"Chest buttons"=false - helps, and you can still use Deposit Button in your inventory, but still crashes if machines from this mod nearby.

**Comment by CD4017BE** [comment]
We already had this problem and according to Vazkii/Quark#36 it was fixed. Try updating Quark

**Comment by Tander** [comment]
It's Quark-beta-28 (latest on curse for now) and still crashes.

**Comment by Tander** [comment]
Still crashes.
http://pastebin.com/MW2vBT2V

Quark-beta-29
InductiveAutomation-1.9.4-5.1.0

**Comment by CD4017BE** [comment]
InductiveAutomation-1.9.4-5.1.0 is not the latest version. The one that fixes it is: [5.1.1](https://github.com/CD4017BE/InductiveAutomation/releases/tag/v5.1.1)

**Comment by Tander** [comment]
It's nice, but I can't add versions that you didn't upload on Curse due rules for modpack makers. Could you upload latest version on Curse?

**Comment by CD4017BE** [comment]
It's already uploaded on curse since yesterday. It seems that curse has a bit delay sometimes.
